spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

server:
  forward-headers-strategy: native
  compression:
    enabled: true

camunda:
  bpm:
    admin-user:
      password: ${CIBSEVEN_ADMIN_PASSWORD}

cibseven:
  webclient:
    authentication:
      jwtSecret: ${CIBSEVEN_WEBCLIENT_AUTHENTICATION_JWTSECRET}
    engine-rest:
      url: ${CIBSEVEN_ENGINE_REST_URL}
    engineRest:
      url: ${CIBSEVEN_ENGINE_REST_URL}

cors:
  enabled: ${CORS_ENABLED:false}
  allowed-origin: ${CORS_ORIGIN:*}
