camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    filter:
      create: All Tasks
    authorization:
      enabled: true
    generic-properties:
      properties:
        historyTimeToLive: "P180D"
        useCibSevenNamespaceInScripting: true
        useCibSevenNamespaceInReflection: true
    webapp:
      header-security:
        content-security-policy-value: font-src 'self' data:;
  bpmn:
    authorization:
      enabled: true
#    webapp:
#      application-path: /
spring:
  profiles:
    active: local

## Server configuration for reverse proxy (HTTPS)
server:
  forward-headers-strategy: native
  compression:
    enabled: true

springdoc:
  swagger-ui:
    enabled: true
    path: /config
    disable-swagger-default-url: true
    urls-primary-name: Classroom API
    urls:
      - name: CIB seven REST API
        url: /cibseven-rest/openapi.json

cibseven:
  webclient:
    authentication:
      jwtSecret: ${CIBSEVEN_WEBCLIENT_AUTHENTICATION_JWTSECRET:}
    engine-rest:
      url: http://localhost:8080
      path: /engine-rest
      display-name: Local Server
      tooltip: Embedded CIB seven engine
    engineRest:
      url: http://localhost:8080
      path: /engine-rest
#  jersey:
#    application-path: /rest
#  datasource:
#    url: jdbc:h2:file:./data/cibseven
#    username: sa
#    password: sa
## Uncomment the following lines to enable the h2 DB console:
#  h2:
#    console:
#      enabled: true
#      path: /console

## Uncomment the following lines to change to port number:
#server:
#  port: 8081
